version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobapps
      SPRING_DATASOURCE_USERNAME: jobuser
      SPRING_DATASOURCE_PASSWORD: jobpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jobapps
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: