#actuator
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: 'prometheus,health,caches'


job:
  api:
    base-url: http://localhost:8000
    read-timeout: 300
    connection-timeout: 10
#db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:jobuser}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobapps}
    password: ${SPRING_DATASOURCE_PASSWORD:jobpassword}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}

  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded

scraper:
  fixedDelay: PT1H
  queries:
    - jobTitle: "Java developer"
      country: "fr"
      pages: 1
      source: "indeed"
    - jobTitle: "Spring developer"
      country: "fr"
      pages: 1
      source: "indeed"


springdoc:
  version: '@org.springdoc.openapi.version@'
  show-actuator: 'true'
  cache:
    disabled: true
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    operations-sorter: method
    groups-order: desc
    use-root-path: true
    disable-swagger-default-url: true

logging:
  level:
    com.ayagmar.go.jobscraper.api.JobScraperApi: WARN

